/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SSIdImport } from './routes/s/$sId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SSIdRoute = SSIdImport.update({
  id: '/s/$sId',
  path: '/s/$sId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/s/$sId': {
      id: '/s/$sId'
      path: '/s/$sId'
      fullPath: '/s/$sId'
      preLoaderRoute: typeof SSIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$sId': typeof SSIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$sId': typeof SSIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/s/$sId': typeof SSIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$sId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$sId'
  id: '__root__' | '/' | '/s/$sId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SSIdRoute: typeof SSIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SSIdRoute: SSIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/s/$sId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/s/$sId": {
      "filePath": "s/$sId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
