services:
  db:
    image: postgres:16
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: dev-api
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ./server/.env
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    volumes:
      - ./server/src:/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    container_name: dev-client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src/ # mounted whole src to avoid missing reload on new files
      - ./client/public:/app/public
    env_file: .env

volumes:
  pgdata:
